config/routes.rb
Rails.application.routes.draw do
  root to: 'commits#index'
  post "fetch_commits" => "github#fetch"
  get "search" => "commits#search"
  resources :users, :commits
end

app/models/commit.rb
class Commit < ActiveRecord::Base
  attr_accessor :page
  
  def self.pages(page_number, count, ordering)
    paginate(per_page: count, page: page_number).order(ordering)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, uniqueness: true

  def self.find_commits(email, page, count, order)
    user = find_by(email: email)
    user_commits = user.nil? ? Commit.none : Commit.where(username: user.name)
    user_commits.pages(page, count, order)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/commits_controller.rb
class CommitsController < ApplicationController
  def index
    commits = Commit.pages(params[:page], 20, 'created_at DESC')
    render locals: { commits: commits, page: params[:page] }
  end

  def search
    commits = User.find_commits(params[:search][:email], params[:page], 20, 'created_at DESC')
    render locals: { commits: commits, page: params[:page] }
  end

  def edit
    render locals: { commit: Commit.find(params[:id]), page: params[:page] }
  end

  def update
    Commit.find(params[:id]).update(commit_params)
    render :index, locals: { commits: Commit.pages(params[:page], 20, 'created_at DESC'), page: params[:page] }
  end

  private

  def commit_params
    params.require(:commit).permit(:username, :page)
  end
end

app/controllers/github_controller.rb
class GithubController < ApplicationController
  def fetch
    FetchCommitsJob.perform_later api_params
    redirect_to root_path, notice: t(:job_enqueued)
  end

  private

  def api_params
    params.require(:repo_path).permit(:user, :repo)
  end
end

app/helpers/commits_helper.rb
module CommitsHelper
  def pagination(commits)
    content_tag(:div, class: 'row col-md-4 col-md-offset-4') do
      js_will_paginate commits, params: { controller: 'commits', action: 'index', url: commits_path }
    end
  end

  def search_form(commits, page)
    if commits.any?
      render 'table', commits: commits, page: page
    else
      content_tag(:div, class:"col-md-12 h1") { t(:nothing_found) }
    end
  end

  def tr_selector(id)
    "commit_#{id}"
  end

  def form_selector(id)
    "commit_form_#{id}"
  end
end

app/helpers/will_paginate_helper.rb
module WillPaginateHelper
  class WillPaginateJSLinkRenderer < WillPaginate::ActionView::LinkRenderer
    def prepare(collection, options, template)
      options[:params] ||= {}
      options[:params]['_'] = nil
      super(collection, options, template)
    end

    protected
    def link(text, target, attributes = {})
      if target.is_a? Fixnum
        attributes[:rel] = rel_value(target)
        target = url(target)
      end

      @template.link_to(target, attributes.merge(remote: true)) do
        text.to_s.html_safe
      end
    end
  end

  def js_will_paginate(collection, options = {})
    will_paginate(collection, options.merge(:renderer => WillPaginateHelper::WillPaginateJSLinkRenderer))
  end
end

app/views/commits/_edit.html.erb
<div class="form-group" id=<%= form_selector(commit.id) %> >
  <%= simple_form_for commit, remote: true do |f| %>
    <%= f.input :username %>
    <%= f.hidden_field :page, value: page %>
    <%= f.button :submit, (t 'save'), name: "submit" %>
    <%= content_tag("a", t("cancel"), class: "btn btn-default", id: "cancel_btn") %>
  <% end %>
</div>

app/views/commits/_search.html.erb
<div class="col-xs-12" style="height:130px;"></div>
<div class="col-md-8 col-md-offset-4" id="form_container">
  <div class="form-inline form-group">
    <%= simple_form_for :search, url: url_for(action: 'search', controller: 'commits'),
                                      method: 'get' do |f| %>
      <%= f.input :email, required: true, autofocus: true, placeholder: "Committer's email",
                                          label: false %>
      <%= f.button :submit, (t :search), id: "search_btn" %>
    <% end %>
  </div>
</div>

app/views/commits/_table.html.erb
<div id="commits_table">
<table class="table table-hover table-striped table-condensed">
  <tr>
    <th><%= t 'commit.date' %></th>
    <th><%= t 'commit.sha' %></th>
    <th><%= t 'commit.description' %></th>
    <th><%= t 'commit.user' %></th>
    <th><%= t 'commit.edit' %></th>
  </tr>
  <% commits.each do |c| %>

  <tr id=<%= tr_selector(c.id) %> >
    <td><%= c.date %></td>
    <td><%= c.sha %></td>
    <td><%= c.description %></td>
    <td><%= c.username %></td>
    <td><%= link_to t('commit.edit'), edit_commit_path(c, page: page), remote: true %></td>
  </tr>
  <% end %>
</table>
<%= pagination(commits) %>
</div>

app/views/commits/edit.js.erb
var elem = "#commit_<%= commit.id %>"
var form = "#commit_form_<%= commit.id %>"
$(elem).after("<%= escape_javascript(render partial: 'edit', locals:{ commit: commit, page: page } ) %>").
  each(function(){
    $("#cancel_btn").on("click", function(){
      $(form).remove();
    })
  });

app/views/commits/index.html.erb
<% if commits.any? %>
  <%= render 'search' %>
  <%= render 'table', commits: commits, page: page %>
<% end %>

<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
<% end %>

app/views/commits/index.js.erb
$('#commits_table').remove()
$('#form_container').after("<%= escape_javascript(render partial: 'table', locals:{ commits: commits, page: page } ) %>")

<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
<% end %>

app/views/commits/search.html.erb
<%= render 'search' %>

<%= search_form(commits, page) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CommitInfo</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'bootstrap', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="col-md-6 col-md-offset-3" id="welcome">
      <h1><%= link_to t(:welcome), root_path %></h1>
      <div class="col-xs-12" style="height:30px;"></div>
      <div class="form-inline form-group">
      <%= simple_form_for :repo_path, url: url_for(action: 'fetch', controller: 'github'),
                                      method: 'post' do |f| %>
        <%= f.input :user, required: true, autofocus: true, placeholder: "User",
                                                            label: false %>
        /
        <%= f.input :repo, required: true, autofocus: true, placeholder: "Repository",
                                                            label: false %>
        <%= f.button :submit, (t :import) %>
      <% end %>
      </div>
    </div>
    <%= yield %>
  </div>
</body>
</html>